import os
import json
import argparse

from typing import List

import data_process.check_sentence as check_sentence

parser = argparse.ArgumentParser(description="Process Natural Statement Generated by GPT")
parser.add_argument("--input_file_path",type=str,help="Path to input file.")
parser.add_argument("--output_file_path",type=str,help="Path to output file.")
args = parser.parse_args()

file_path = args.input_file_path
file_name = os.listdir(file_path)

print("文件数量:",len(file_name))

sum_valid = 0   # 合并成功语句数量
sum_invalid = 0  # 无法合并语句数量
sum = 0
all_dicts = []

for name in file_name:
    path = file_path + name
    with open(path,'r',encoding='utf-8') as f:
        data = json.load(f)
        try:
            d = eval(data)
            datas = dict()
            formal = str(d['表达式'])
            formal = formal.replace('{','')
            formal = formal.replace("}",'')
            formal = formal.replace("'",'')
            formal = formal.replace('\\u3000','')
            formal = formal.replace("其他",'')
            formal = formal.replace("其它",'')

            datas['表达式'] = formal
            datas['自然语句'] = []

            sentences = list(d['自然语句'].values())

            for sentence in sentences:
                if check_sentence.check(sentence,formal):
                    datas['自然语句'].append(sentence)

            if len(datas['自然语句']) > 0:
                all_dicts.append(datas)
                sum_valid += 1
            else:
                sum += 1

        except:
            sum_invalid += 1

        f.close()

print("valid:",sum_valid)
print("invalid:",sum_invalid)
print("len=0:",sum)

file = open(args.output_file_path,'w',encoding='utf-8')
json.dump(all_dicts,file,ensure_ascii=False)
file.close()

