operators = [
             {'operator': '金融指标变化', 'concepts': ['金融指标', '公司', '时间段','升降']},
             {'operator': '金融指标市场预期值变化', 'concepts': ['金融指标','公司', '时间段','升降']},
             {'operator': '行业集中度状况', 'concepts': ['行业', '时间','高低']},
             {'operator': '市场份额', 'concepts': ['公司', '行业', '时间','百分数']},
             {'operator': '集中度指数', 'concepts': ['行业','地点','时间','百分数']},
             {'operator': '赫芬达指数', 'concepts': ['行业','地点','时间','百分数']},
             {'operator': '克拉夫特指数', 'concepts': ['行业','地点','时间','百分数']},
             {'operator': '竞争强度指数', 'concepts': ['行业','地点','时间','百分数']},
             {'operator': 'CR4', 'concepts': ['行业','地点','时间','百分数']},
             {'operator': 'CR8', 'concepts': ['行业','地点','时间','百分数']},
             {'operator': '市场准入壁垒状况', 'concepts': ['行业','地点','时间','高低']},
             {'operator': '平均注册资本要求', 'concepts': ['行业','地点','时间','资金']},
             {'operator': '专利数量或知识产权拥有者比例', 'concepts': ['行业','地点','时间','百分数']},
             {'operator': '平均获得监管审批所需的时间','concepts': ['行业','地点','时间','时限']},
             {'operator': '研发投入比例','concepts': ['公司','行业','时间','百分数']},
             {'operator': '用户增长率','concepts': ['公司','时间','百分数']},
             {'operator': '品牌知名度评分','concepts': ['公司','时间','评分']},
             {'operator': '市场经济状况','concepts': ['行业','时间','市场状况']},
             {'operator': 'GDP','concepts': ['地点','时间','gdp']},
             {'operator': '通货膨胀率','concepts': ['地点','时间段','百分数']},
             {'operator': '债务总额','concepts': ['国家','时间','资金']},
             {'operator': '用户粘性状况','concepts': ['公司','时间','升降']},
             {'operator': '客户续订率','concepts': ['公司','产品','时间','百分数']},
             {'operator': '用户留存率','concepts': ['公司','产品','时间','百分数']},
             {'operator': '用户反弹率','concepts': ['公司','产品','时间','百分数']},
             {'operator': '平均用户收益','concepts': ['公司','时间段','资金']},
             {'operator': '竞争格局状况','concepts': ['行业','时间','格局']},
             {'operator': '价格竞争指数','concepts': ['行业产品','时间','百分数']},
             {'operator': '市场创新率','concepts': ['行业','地点','时间段','百分数']},
             {'operator': '市场进入率','concepts': ['行业','地点','时间段','百分数']},
             {'operator': '市场退出率','concepts': ['行业','地点','时间段','百分数']},
             {'operator': '消费者需求强度','concepts': ['行业产品','时间','强弱']},
             {'operator': '市场发展潜力','concepts': ['行业产品','时间','大小']},
             {'operator': '利润','concepts': ['公司','时间','资金']},
             {'operator': '收入','concepts': ['公司','时间段','资金']},
             {'operator': '价格','concepts': ['产品','时间','价格']},
             {'operator': '营业收入','concepts': ['公司','时间段','资金']},
             {'operator': '归母净利润','concepts': ['公司','时间段','百分数']},
             {'operator': '毛利率','concepts': ['公司','时间段','百分数']},
             {'operator': '成本价格','concepts': ['公司','产品','成本类型','时间','价格']},
             {'operator': '净利率','concepts': ['公司','时间段','百分数']},
             {'operator': '市占率','concepts': ['公司','行业','时间','百分数']},
             {'operator': '营销成本','concepts': ['公司','产品','时间','价格']},
             {'operator': '进口依赖度','concepts': ['国家','资源','时间','大小']},
             {'operator': '渗透率','concepts': ['产品','时间','百分数']},
             {'operator': 'PMI','concepts': ['行业','时间','百分数']},
             {'operator': '摊薄EPS','concepts': ['公司','时间段','EPS']},
             {'operator': '扣非归母净利润','concepts': ['公司','时间段','资金']},
             {'operator': '判别','concepts': ['公司','行业','时间','判别']},
             {'operator': '判别','concepts': ['公司','产品','时间','判别']},
             {'operator': '判别','concepts': ['产品','行业','时间','判别']},
             {'operator': '收入增长率','concepts': ['公司','产品','时间段','百分数']},
             {'operator': '利润增速','concepts': ['公司','产品','时间段','百分数']},
             {'operator': '大公司数目','concepts': ['行业','时间','企业数量']},
             {'operator': '中小公司数目','concepts': ['行业','时间','企业数量']},
             {'operator': '公众舆论倾向','concepts': ['公司','时间','舆论倾向']},
             {'operator': '人口数目','concepts': ['地点','时间','人数']},
             {'operator': '人口平均收入水平','concepts': ['地点','时间','工资']},
             {'operator': '市场透明度','concepts': ['行业','时间','高低']},
             {'operator': '透明度指数','concepts': ['行业','地点','时间','百分数']},
             {'operator': '交易清算周期','concepts': ['行业','地点','时间','时限']},
             {'operator': '资产定价透明度','concepts': ['行业','地点','时间','百分数']},
             {'operator': '整体市场效率','concepts': ['行业','时间','百分数']},
             {'operator': '市场规模','concepts': ['行业','时间','大小']},
             {'operator': '税收','concepts': ['公司','时间','资金']},
             {'operator': '知识产权保护强度','concepts': ['行业','时间','强弱']},
             {'operator': '就业率','concepts': ['行业','地点','时间','百分数']},
             {'operator': '消费者信心指数','concepts': ['行业产品','时间','百分数']},
             {'operator': '日常用品价格','concepts': ['产品','时间','价格']},
             {'operator': '判别是否有准入许可','concepts': ['行业','时间','判别']},
             {'operator': '供应链复杂度','concepts': ['行业','时间','复杂度']},
             {'operator': '行业生命周期状况','concepts': ['行业','时间','周期性']},
             {'operator': '市场敏感度','concepts': ['行业','时间','高低']},
             {'operator': '市场饱和度','concepts': ['行业产品','时间','百分数']},
             {'operator': '市场增长率','concepts': ['行业','地点','时间','百分数']},
             {'operator': '市场饱和度指数','concepts': ['行业','地点','时间','百分数']},
             {'operator': '利润率','concepts': ['公司','产品','时间','百分数']},
             {'operator': '失业率','concepts': ['行业','地点','时间','百分数']},
             {'operator': '社会福利压力','concepts': ['地点','时间','大小']},
             {'operator': '居民消费意愿强度','concepts': ['地点','时间','强弱']},
             {'operator': '居民投资意愿强度','concepts': ['地点','时间','强弱']},
             {'operator': '居民贷款量','concepts': ['地点','时间','资金']},
             {'operator': '金融机构存款','concepts': ['公司','时间','资金']},
             {'operator': '生产资料价格','concepts': ['公司','行业','时间','资金']},
             {'operator': 'PPI','concepts': ['产品','时间','百分数']},
             {'operator': 'CPI','concepts': ['产品','时间','百分数']},
             {'operator': '经济回复速度','concepts': ['行业','时间','速度']},
             {'operator': '经济复苏斜率','concepts': ['行业','时间','大小']},
             {'operator': '净融资额','concepts': ['行业','时间','资金']},
             {'operator': '债券收益','concepts': ['地点','时间','资金']},
             {'operator': '行业状态','concepts': ['行业','时间','行业状态']},
             {'operator': '判断行业所处地点','concepts': ['行业','地点','时间','判别']},
             {'operator': '加息幅度','concepts': ['公司','时间','大小']},
             {'operator': '抵押贷款利率','concepts': ['地点','年数','百分数']},
             {'operator': '货币指数','concepts': ['货币种类','时间','百分数']},
             {'operator': '出口压力','concepts': ['地点','产品','时间','大小']},
             {'operator': '经济复苏力度','concepts': ['地点','时间','强弱']},
             {'operator': 'PMI指数','concepts': ['行业','地点','时间','百分数']},
             {'operator': '劳动力市场缺口程度','concepts': ['行业','地点','时间','大小']},
             {'operator': '经济增长速度','concepts': ['地点','时间','速度']},
             {'operator': '经济增长趋势速度','concepts': ['地点','时间','速度']},
             {'operator': '全要素生产率','concepts': ['地点','时间','百分数']},
             {'operator': '储蓄回报率','concepts': ['地点','时间','百分数']},
             {'operator': '投资回报率','concepts': ['地点','时间','高低']},
             {'operator': '企业对外投资意愿','concepts': ['地点','时间','强弱']},
             {'operator': '企业所得税税率','concepts': ['行业','地点','时间','百分数']},
             {'operator': '人口老龄化程度','concepts': ['地点','时间','程度']},
             {'operator': '货币价值','concepts': ['货币种类','时间','价格']},
             {'operator': '产业空心化程度','concepts': ['行业','地点','时间','高低']},
             {'operator': '扩散指数','concepts': ['行业','地点','时间','百分数']},
             {'operator': '劳动参与率','concepts': ['行业','地点','时间','百分数']},
             {'operator': '就业人口数目','concepts': ['行业','地点','时间','人数']},
             {'operator': '失业人口数目','concepts': ['行业','地点','时间','人数']},
             {'operator': '劳动力人口数目','concepts': ['行业','地点','时间','人数']},
             {'operator': '非农就业人口数目','concepts': ['行业','地点','时间','人数']},
             {'operator': '劳动市场平均工资','concepts': ['行业','地点','时间','工资']},
             {'operator': '消费信贷水平','concepts': ['地点','时间','高低']},
             {'operator': '工业产值','concepts': ['地点','时间','资金']},
             {'operator': '平均工资','concepts': ['行业','地点','时间','工资']},
             {'operator': '职位空缺数目','concepts': ['行业','地点','时间','数目']},
             {'operator': '通胀水平回落速度','concepts': ['地点','时间','速度']},
             {'operator': '就业市场紧张状况','concepts': ['行业','地点','时间','程度']},
             {'operator': '移民数目','concepts': ['地点','时间段','人数']},
             {'operator': '金融机构加权平均存款准备率','concepts': ['地点','时间','百分数']},
             {'operator': '净储蓄率','concepts': ['地点','时间','百分数']},
             {'operator': '职业空缺率','concepts': ['行业','地点','时间','百分数']},
             {'operator': '人口密度','concepts': ['地点','时间','密度']},
             {'operator': '供应链效果','concepts': ['公司','时间','效果']},
             {'operator': '社交影响力','concepts': ['公司','时间','大小']},
             {'operator': '消费者满意程度','concepts': ['公司','时间','高低']},
             {'operator': '供应链韧性','concepts': ['公司','时间','强弱']},
             {'operator': '市场稳定性','concepts': ['行业','时间','高低']},
             {'operator': '供应链多样性','concepts': ['行业产品','时间','高低']},
             {'operator': '消费者价格敏感程度','concepts': ['行业产品','时间','高低']},
             {'operator': '供应链透明度','concepts': ['行业产品','时间','高低']},
             {'operator': '市场成熟度','concepts': ['行业','时间','高低']},
             {'operator': '产品可替代性','concepts': ['产品','时间','高低']},
             {'operator': '培养机构数目','concepts': ['行业','时间','地点','企业数量']},
             {'operator': '销售量','concepts': ['公司','产品','时间','单数']},
             {'operator': '营业成本','concepts': ['公司','行业','时间','资金']},
             {'operator': '通胀水平','concepts': ['地点','时间','高低']},
             {'operator': '通胀率','concepts': ['地点','时间','百分数']},
             {'operator': '议价能力','concepts': ['公司','行业产品','时间','强弱']},
             {'operator': '业务量','concepts': ['公司','产品','时间','单数']},
             {'operator': '判断公司主营业务相关性','concepts': ['公司','行业','时间','判别']},
             {'operator': '供应量状况','concepts': ['公司','产品','时间','供应量']},
             {'operator': '物价水平','concepts': ['地点','时间','高低']},
             {'operator': 'SLR','concepts': ['地点','时间','百分数']},
             {'operator': '品牌影响力状况','concepts': ['行业','品牌','时间','大小']},
             {'operator': '技术壁垒状况','concepts': ['行业','时间','高低']},
             {'operator': '产量','concepts':['产品','时间段','数目']},
             {'operator': '需求量','concepts':['国家','产品','时间','数目']},
             {'operator': '需求量','concepts':['公司','产品','时间','数目']},
             {'operator': '储备量','concepts':['国家','产品','时间','数目']},
             {'operator': '出口量','concepts':['国家','产品','时间','数目']},
             {'operator': '出口量','concepts':['公司','产品','时间','数目']},
             {'operator': '进口量','concepts':['公司','产品','时间','数目']},
             {'operator': '出货量','concepts':['公司','产品','时间','数目']},
             {'operator': '能源价格','concepts':['资源','时间','价格']},
             {'operator': '资本市场开发程度','concepts':['行业','时间','程度']},
            #############################新增表达式#####################################
             {'operator': '上游产品','concepts': ['产品','产品']},
             {'operator': '下游产品','concepts': ['产品','产品']},
             {'operator': '预测价格','concepts': ['产品','时间','价格']},
             {'operator': '公司业务','concepts': ['公司','行业']},
             ]
              # {'operator': '其他算子', 'concepts': ['概念1', '概念2', '概念3']}

operator_dict = {}
for dct in operators:
    operator_dict[dct['operator']] = dct['concepts']
